### ISSUE TITLE
Allow (dynamic?) linking to existing libFLAC library?

### ISSUE THREAD

**Issue by mgeier** [mgeier/libflac-sys#1]
For example, https://github.com/rusqlite/rusqlite can link to an existing library, but it also has the `bundled` feature which builds the lib from source.

https://github.com/rust-lang/pkg-config-rs could be used to detect an existing library.

https://github.com/mcgoo/vcpkg-rs could be used on MSVC, there seems to be a package for libFLAC: https://github.com/Microsoft/vcpkg/tree/master/ports/libflac.

**Comment by nabijaczleweli** [comment]
To use just the distribution `libFLAC`/`libogg`, then replacing the entire `build.rs` with just
```rust
fn main() {
    if cfg!(feature = "ogg") {
        println!("cargo:rustc-link-lib=ogg");
    }
    println!("cargo:rustc-link-lib=FLAC");
}
```
worked for me on MSYS2 and Debian, with the correct packages. Wrapping this in some sort of feature seems easy enough. (Note the lack of explicit KIND, since some distributions' libFLAC will be static, it's better to let the linker Just figure it out.)

**Comment by mgeier** [comment]
I think it would be good to build from source by default (because only then we can ensure the version of the headers matches the version of the lib) and only link to an existing library when explicitly requested.

@nabijaczleweli Would you like to make a PR for that?

**Comment by nabijaczleweli** [comment]
it'd conflict with #5, but after that's resolved, sure
