### ISSUE TITLE
Use MSYS2 in CI?

### ISSUE THREAD

**Issue by mgeier** [mgeier/libflac-sys#12]
@nabijaczleweli You mentioned in #5 that there was a build error with MSYS2, right?

Can/should we add this to CI in order to detect such problems in the future?

Is MSYS2 supported on Github Actions?

**Comment by nabijaczleweli** [comment]
"github actions msys2" points to https://github.com/msys2/setup-msys2 which lists caveats and
> MSYS2 is available by default in windows-latest virtual environment for GitHub Actions, located at C:\msys64. 

But I'm far from a Github Actions Enjoyer:tm: so dunno how well either the builtin or the script work.

That being said, MSYS2 is definitely Archware and it [shows](https://github.com/nabijaczleweli/cargo-update/blob/96551827f4a5244dd2d54e29dc8b7103e6354398/appveyor.yml) (the header patches are probably not needed for libflac-sys, copying `libFLAC.dll.a` from either of the three locations it ends up in and I graciously forgot since the last time would be). If I didn't use it on a daily basis I wouldn't bother maintaining CI for it, fact is, but it *is* a Relatively Sensible Environment But On Windows and it beats getting concussions from the nearest wall attempting to get any part of MSVC to behave at all sanely. Computing was a mistake.

The build error was that some of the FLAC binaries required system-specific bits, obviously not present on NT (I've also thankfully managed to forget the specifics), so the likelihood of it reappearing is low to nil.

**Comment by mgeier** [comment]
OK, thanks for your insights, so I'll close this for now.

If anybody needs this in the future, please leave a comment or create a PR!

**Comment by mgeier** [comment]
In the meantime, I've learned how to use MSYS2 on Github Actions and I've just created a PR: #23.
