### ISSUE TITLE
Update for FLAC 1.4.2

### ISSUE THREAD

**Issue by Vaporeon** [mgeier/libflac-sys#25]
The 1.4.x series comes with a large amount of improvements.

**Comment by mgeier** [comment]
> Looks like libssp is not getting linked?

Yeah, looks like it, but why?

I tried it with more verbosity (see https://github.com/mgeier-forks/libflac-sys/actions/runs/3464428567/jobs/5785940249) and I'm seeing this:

    -- Looking for __stack_chk_fail in ssp.a - found

Which looks like the library is actually found.

However, I don't know whether it is correctly passed to the compiler.
I can't find "ssp" anywhere else in the log.

It should be added with

    link_libraries("ssp.a")

... according to https://github.com/xiph/flac/blob/1.4.2/CMakeLists.txt#L142-L151

But is it?

> Unrelated, but now `FLAC__NO_DLL` needs to be defined somewhere to get a real static build, not sure if that would be relevant to this crate.

It looks like this is set automatically by CMake if `BUILD_SHARED_LIBS` is off (which it is by default): https://github.com/xiph/flac/blob/1.3.4/src/libFLAC/CMakeLists.txt#L87-L89

The verbose log mentioned above has `-DFLAC__NO_DLL` all over the place, so this seems to be fine.

**Comment by mgeier** [comment]
I compared the (verbose) `windows-gnu` and `MSYS2` outputs, and in none of them `ssp.a` is added to the compiler arguments. I guess since we are building a static library (`libFLAC.a`), other static libraries (like `libssp.a`) are not linked, but are supposed to be provided alongside other static libraries in later build steps.

I suspect that somehow (but I don't know how), the `ssp` library is available to MSYS2 without having to specify it explicitly in the compiler arguments.

Anyway, I don't know how to investigate this further, so I decided to simply drop `windows-gnu` from CI. All remaining tests pass now.

I think this is not too bad, because we still have a working non-MSVC toolchain for Windows with MSYS2.

**Comment by Vaporeon** [comment]
That is unfortunate, we exclusively use windows-gnu to cross compile static Windows builds from Linux.
I have tested this git repo and get the same linking error you had with CI, however the 0.2.2 release works.
I wonder what changed?

**Comment by Vaporeon** [comment]
I found a workaround, I'll make a pull request

**Comment by mgeier** [comment]
The mentioned pull request is here: #29.
However, I think I would prefer to merge #30 instead.

**Comment by mgeier** [comment]
I have just merged #30, which did the requested update.
